CommonProcessor/CommonProcessor/CommonProcessor/Controllers/BpSalesReportController.cs
using CommonProcessor.DAL;
using CommonProcessor.Models.DbContext;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace CommonProcessor.Controllers
{
    public class BpSalesReportController : Controller
    {
        private readonly BpPromotionDal _brandPromotionDal;

        public BpSalesReportController()
        {
            //_wDMSDal = new WDMSDal(new WDSEntities());
            _brandPromotionDal = new BpPromotionDal(new BrandPromotionEntities());

        }
        // GET: BpSalesReport
        [SessionCheck]
        public ActionResult Index()
        {
            return View();
        }

        public async Task<ActionResult> GetBpSalesReportData(DateTime fromDate, DateTime todate)
        {
            var data = await _brandPromotionDal.GetBpSalesReportData(fromDate, todate);

            var returnObj = new
            {
                Data = data,
            };
            return new JsonResult()
            {
                Data = returnObj,
                MaxJsonLength = 86753090,
                JsonRequestBehavior = JsonRequestBehavior.AllowGet
            };

        }

        [SessionCheck]
        [HttpGet]
        public async Task<ActionResult> GetBPPilotReportData()
        {
            return View();
        }

        public async Task<ActionResult> GetBPPilotReportData(DateTime fromDate, DateTime todate, string ddlPhn)
        {
            var data = await _brandPromotionDal.GetBpWiseSalesReportData(fromDate, todate, ddlPhn);

            var returnObj = new
            {
                Data = data,
            };
            return new JsonResult()
            {
                Data = returnObj,
                MaxJsonLength = 86753090,
                JsonRequestBehavior = JsonRequestBehavior.AllowGet
            };

        }

        //[SessionCheck]
        [HttpGet]
        public async Task<ActionResult> GetBPWiseSalesQtyReport()
        {
            return View();
        }

        public async Task<ActionResult> GetBPWiseSalesQtyReport(DateTime fromDate, DateTime todate)
        {
            var data = await _brandPromotionDal.GetBPWiseSalesQtyReport(fromDate, todate);

            var returnObj = new
            {
                Data = data,
            };
            return new JsonResult()
            {
                Data = returnObj,
                MaxJsonLength = 86753090,
                JsonRequestBehavior = JsonRequestBehavior.AllowGet
            };

        }
    }
}

CommonProcessor/CommonProcessor/CommonProcessor/Controllers/BpSetupController.cs
using CommonProcessor.DAL;
using CommonProcessor.Models.DbContext;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace CommonProcessor.Controllers
{
    public class BpSetupController : Controller
    {
        //private readonly WDMSDal _wDMSDal;
        private readonly BpPromotionDal _brandPromotionDal;
        private readonly RBSYNERGYDal _rBSYNERGYDal;
        public BpSetupController()
        {
            //_wDMSDal = new WDMSDal(new WDSEntities());
            _brandPromotionDal = new BpPromotionDal(new BrandPromotionEntities());
            _rBSYNERGYDal = new RBSYNERGYDal(new RBSYNERGYEntities()/*, new RestaurantDBEntities()*/);

        }

        // GET: BpSetup
        [SessionCheck]
        public ActionResult Index()
        {
            //GetAllActiveBP();
            return View();
        }

        public async Task<ActionResult> GetABpByMobileNumber(string BPPhoneNumber)
        {
            var data = await _brandPromotionDal.GetABpByMobileNumber(BPPhoneNumber);

            var returnObj = new
            {
                Data = data,
            };
            return new JsonResult()
            {
                Data = returnObj,
                MaxJsonLength = 86753090,
                JsonRequestBehavior = JsonRequestBehavior.AllowGet
            };

        }

        public async Task<ActionResult> GetADealerByEbsCode(string DealerCode)
        {
            var data = await _rBSYNERGYDal.GetADealerByEbsCode(DealerCode);

            var returnObj = new
            {
                Data = data,
            };
            return new JsonResult()
            {
                Data = returnObj,
                MaxJsonLength = 86753090,
                JsonRequestBehavior = JsonRequestBehavior.AllowGet
            };

        }

        public async Task<ActionResult> GetAllActiveBP()
        {
            var data = await _brandPromotionDal.GetAllActiveBP();

            var returnObj = new
            {
                Data = data,
            };
            return new JsonResult()
            {
                Data = returnObj,
                MaxJsonLength = 86753090,
                JsonRequestBehavior = JsonRequestBehavior.AllowGet
            };

        }

        public async Task<ActionResult> AddOrEditBP(string EbsCode, string DealerCode, string DealerName, string District, string RetailerID, string RetailerName, string RetailerAddress, string RetailerPhoneNumber, string BpPhoneNumber, string BpName, bool IsActive)//Start to WORK
        {
            var data = await _brandPromotionDal.AddOrEditBP(EbsCode, DealerCode, DealerName, District, RetailerID, RetailerName, RetailerAddress, RetailerPhoneNumber, BpPhoneNumber, BpName, IsActive);

            var returnObj = new
            {
                Data = data,
            };
            return new JsonResult()
            {
                Data = returnObj,
                MaxJsonLength = 86753090,
                JsonRequestBehavior = JsonRequestBehavior.AllowGet
            };
            //return null;

        }
    }
}

CommonProcessor/CommonProcessor/CommonProcessor/Views/BpSalesReport/GetBPPilotReportData.cshtml
@{
    ViewBag.Title = "GetBPPilotReportData";
}

<style>
    .selected {
        background-color: aqua;
    }

    .excelBtn {
        color: #f8f9fa !important;
        background-color: #0d6efd !important;
        border-color: #0d6efd !important;
        padding: .375rem .75rem !important;
        font-size: 1rem !important;
        border-radius: .25rem !important;
    }

    .swal2-icon {
        margin: 0px !important;
    }
</style>

<br />
<div class="card">
    <div class="card-body">

        <div class="row">

            <div class="col-sm-3">
                <div class="input-group mb-3">
                    <span class="input-group-text" id="basic-addon1"><b>Start Date</b></span>
                    <input type="date" class="form-control" id="startDate" />
                </div>
            </div>
            <div class="col-sm-3">
                <div class="input-group mb-3">
                    <span class="input-group-text" id="basic-addon1"><b>End Date</b></span>
                    <input type="date" class="form-control" id="endDate" />
                </div>
            </div>

            <div class="col-sm-3">
                <div class="input-group mb-3">
                    <span class="input-group-text" id="type"><b>Phone</b></span>
                    <select class="form-control" style="width: 60%" multiple="multiple" id="ddlPhn">
                    </select>
                </div>
            </div>

            <div class="col-sm-2">
                <div class="input-group mb-3">
                    <input type="button" class="btn btn-danger btn-group-lg col-md-4" id="BtnSearch" value="Search" />
                </div>
            </div>
        </div>
    </div>
</div>
<br />
<div class="card">
    <div class="card-header">

        <h3>Total Count: <span class="badge bg-success" id="totalCount"></span></h3>

    </div>
    <div class="card-body">
        <div class="row">
            <div style="height: 550px; overflow-x:scroll;overflow-x: auto">
                <table class="table cell-border table-responsive table-hover table-striped" id="recordTable" style="display:none;">
                    <thead>
                        <tr>

                            <th>rn</th>
                            <th>Imei1</th>
                            <th>Imei2</th>
                            <th>Model</th>
                            <th>MSRP</th>
                            <th>BPName</th>
                            <th>BpPhoneMumber</th>
                            <th>RetailerName</th>
                            <th>RetailerAddress</th>
                            <th>DealerCode</th>
                            <th>DealerName</th>
                            <th>Claim_Date</th>
                            <th>Replacement</th>

                        </tr>
                    </thead>
                    <tbody id="recordTableBody">
                    </tbody>
                    <tfoot>
                        <tr>

                            <th>rn</th>
                            <th>Imei1</th>
                            <th>Imei2</th>
                            <th>Model</th>
                            <th>MSRP</th>
                            <th>BPName</th>
                            <th>BpPhoneMumber</th>
                            <th>RetailerName</th>
                            <th>RetailerAddress</th>
                            <th>DealerCode</th>
                            <th>DealerName</th>
                            <th>Claim_Date</th>
                            <th>Replacement</th>

                        </tr>
                    </tfoot>
                </table>
            </div>
        </div>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.5.1.js"></script>

<script src="https://cdn.jsdelivr.net/npm/sweetalert2@10"></script>
<link href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" rel="stylesheet" />

<script>
    $(document).ready(function () {
        //$('#recordTable').DataTable();

        $("#ddlPhn").select2({
            width: 'resolve', // need to override the changed default
            theme: "classic"
        });

        debugger;
        $.ajax({

            type: "GET",
            url: '@Url.Action("GetAllActiveBP", "BpSetup")',
            //data: "{}",
            data: { ddlPhn: $("#ddlPhn").val() },
            success: function (data) {
                debugger;
                var s = '';//<option value="0">ALL</option>
                for (var i = 0; i < data.Data.length; i++) {
                    s += '<option value="' + data.Data[i].bpphonenumber + '">' + data.Data[i].bpphonenumber + '  (' + data.Data[i].bpname + ')</option>';
                }
                $("#ddlPhn").html(s);
            }
        });


        $("#BtnSearch").click(function () {
            debugger;
            var fromDate = $("#startDate").val();
            var todate = $("#endDate").val();
            var ddlPhn = $("#ddlPhn").val();

            var ddlPhn = $('#ddlPhn :selected').map((_, e) => e.value).get().toString();
            var x = ddlPhn.toString();
            //$('#ddlType :selected').each(function () {
            //    ddlType[$(this).val()] = $(this).val();
            //});

            //var ddlType = $("#ddlType").val();
            var dataList = JSON.stringify({ fromDate: fromDate, todate: todate, ddlPhn: ddlPhn });
            if (fromDate != "" && todate != "" && ddlPhn!="") {
                $.ajax({
                    type: 'POST',
                    contentType: 'application/json',
                    dataType: 'json',
                    url: '@Url.Action("GetBPPilotReportData", "BpSalesReport")',
                    data: dataList,
                    beforeSend: function () {
                        $('#cover-spin').show();
                    },
                    success: function (data) {
                        //debugger;
                        var imeiDataList = data.Data.length;
                        $("#totalCount").text(imeiDataList);
                        $("#recordTableBody").html("");
                        $('#recordTable').DataTable().clear().destroy();
                        if (imeiDataList > 0) {
                            for (var i = 0; i < imeiDataList; i++) {

                                var cSharpAddedDate = data.Data[i].Claim_Date;
                                var m = new Date(parseInt(cSharpAddedDate.replace(/[^0-9 +]/g, '')));

                                //var addedDateString = (m.getUTCFullYear() + "-" + (m.getUTCMonth() + 1) + "-" + (m.getUTCDate() + 1));
                                var addedDateString = m.getFullYear() + "-" + (m.getMonth() + 1) + "-" + m.getDate();


                                $("#recordTableBody").append('<tr>' +

                                    '<td style="width: 30%">' +
                                    data.Data[i].rn +
                                    '</td>' +
                                    '<td style="width: 30%">' +
                                    data.Data[i].Imei +
                                    '</td>' +
                                    '<td style="width: 30%">' +
                                    data.Data[i].Imei2 +
                                    '</td>' +
                                    '<td>' +
                                    data.Data[i].Model +
                                    '</td>' +
                                    '<td>' +
                                    data.Data[i].MSRP +
                                    '</td>' +
                                    '<td style="width: 30%">' +
                                    data.Data[i].BPName +
                                    '</td>' +
                                    '<td style="width: 30%">' +
                                    data.Data[i].BpPhoneMumber +
                                    '</td>' +
                                    '<td style="width: 30%">' +
                                    data.Data[i].RetailerName +
                                    '</td>' +
                                    '<td style="width: 30%">' +
                                    data.Data[i].RetailerAddress +
                                    '</td>' +
                                    '<td style="width: 30%">' +
                                    data.Data[i].DealerCode +
                                    '</td>' +
                                    '<td style="width: 30%">' +
                                    data.Data[i].DealerName +
                                    '</td>' +
                                    '<td>' +
                                    addedDateString +
                                    '</td>' +
                                    '<td>' +
                                    data.Data[i].Replacement +
                                    '</td>' +
                                    '</tr>');
                            }
                            $('#recordTable').show();
                            var table = $('#recordTable').DataTable();

                            new $.fn.dataTable.Buttons(table, {
                                buttons: [
                                    { extend: 'excel', className: 'excelBtn', title: 'Bp Pilot Report', text: 'Click For Excel Export' }
                                ]
                            });

                            table.buttons(0, null).container().prependTo(
                                table.table().container()
                            );

                        } else {
                            swal.fire({
                                title: "Message",
                                text: "Data Not Found",
                                icon: "warning",
                                button: "OK",
                                showClass: {
                                    popup: 'animate__animated animate__fadeInDown'
                                },
                                hideClass: {
                                    popup: 'animate__animated animate__fadeOutUp'
                                }
                            });
                        }
                        $('#cover-spin').hide();
                    }
                });
            }

        });
    });
</script>

CommonProcessor/CommonProcessor/CommonProcessor/Views/BpSalesReport/GetBPWiseSalesQtyReport.cshtml
@{
    ViewBag.Title = "GetBPWiseSalesQtyReport";
}

<style>
    .selected {
        background-color: aqua;
    }

    .excelBtn {
        color: #f8f9fa !important;
        background-color: #0d6efd !important;
        border-color: #0d6efd !important;
        padding: .375rem .75rem !important;
        font-size: 1rem !important;
        border-radius: .25rem !important;
    }

    .swal2-icon {
        margin: 0px !important;
    }
</style>

<div class="card-header d-flex align-items-center" style="background-color: cadetblue; color: white;width:auto;">
    <h3 class="h4" style="font-weight: normal">WBC Sales Qty Report</h3>
</div>

<br />
<div class="card">
    <div class="card-body">

        <div class="row">
            <div class="col-sm-4">
                <div class="input-group mb-3">
                    <span class="input-group-text" id="basic-addon1"><b>Start Date</b></span>
                    <input type="date" class="form-control" id="startDate" />
                </div>
            </div>
            <div class="col-sm-4">
                <div class="input-group mb-3">
                    <span class="input-group-text" id="basic-addon1"><b>End Date</b></span>
                    <input type="date" class="form-control" id="endDate" />
                </div>
            </div>
            <div class="col-sm-3">
                <div class="input-group mb-3">
                    <input type="button" class="btn btn-danger btn-group-lg col-md-3" id="BtnSearch" value="Search" />
                </div>
            </div>
        </div>
    </div>
</div>
<br />
<div class="card">
    <div class="card-header">

        <h3>Total Count: <span class="badge bg-success" id="totalCount"></span></h3>

    </div>
    <div class="card-body">
        <div class="row">
            <div style="height: 650px; overflow-x:scroll;overflow-x: auto;width: 100%; overflow-y: auto">
                <table class="table cell-border table-responsive table-hover table-striped" id="recordTable" style="display:none;">
                    <thead>
                        <tr>

                            <th>DealerCode</th>
                            <th>DealerName</th>
                            <th>BpPhoneMumber</th>
                            <th>BPName</th>
                            <th>SALES_QTY</th>

                        </tr>
                    </thead>
                    <tbody id="recordTableBody">
                    </tbody>
                    <tfoot>
                        <tr>

                            <th>DealerCode</th>
                            <th>DealerName</th>
                            <th>BpPhoneMumber</th>
                            <th>BPName</th>
                            <th>SALES_QTY</th>

                        </tr>
                    </tfoot>
                </table>
            </div>
        </div>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.5.1.js"></script>

<script src="https://cdn.jsdelivr.net/npm/sweetalert2@10"></script>
<link href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" rel="stylesheet" />

<script>
    $(document).ready(function () {
        //$('#recordTable').DataTable();

        $("#BtnSearch").click(function () {
            debugger;
            var fromDate = $("#startDate").val();
            var todate = $("#endDate").val();
            var dataList = JSON.stringify({ fromDate: fromDate, todate: todate });
            if (fromDate != "" && todate != "") {
                $.ajax({
                    type: 'POST',
                    contentType: 'application/json',
                    dataType: 'json',
                    url: '@Url.Action("GetBPWiseSalesQtyReport", "BpSalesReport")',
                    data: dataList,
                    beforeSend: function () {
                        debugger;
                        $('#cover-spin').show();
                    },
                    success: function (data) {
                        debugger;
                        var imeiDataList = data.Data.length;
                        $("#totalCount").text(imeiDataList);
                        $("#recordTableBody").html("");
                        $('#recordTable').DataTable().clear().destroy();
                        if (imeiDataList > 0) {
                            for (var i = 0; i < imeiDataList; i++) {

                                
                                $("#recordTableBody").append('<tr>' +

                                    '<td>' +
                                    data.Data[i].DealerCode +
                                    '</td>' +
                                    '<td style="width: 30%">' +
                                    data.Data[i].DealerName +
                                    '</td>' +
                                    '<td style="width: 30%">' +
                                    data.Data[i].BpPhoneMumber +
                                    '</td>' +
                                    '<td style="width: 30%">' +
                                    data.Data[i].BPName +
                                    '</td>' +
                                    '<td>' +
                                    data.Data[i].SALES_QTY +
                                    '</td>' +
                                    '</tr>');
                            }
                            $('#recordTable').show();
                            var table = $('#recordTable').DataTable();

                            new $.fn.dataTable.Buttons(table, {
                                buttons: [
                                    { extend: 'excel', className: 'excelBtn', title: 'Bp Sales Qty Report', text: 'Click For Excel Export' }
                                ]
                            });

                            table.buttons(0, null).container().prependTo(
                                table.table().container()
                            );

                        } else {
                            swal.fire({
                                title: "Message",
                                text: "Data Not Found",
                                icon: "warning",
                                button: "OK",
                                showClass: {
                                    popup: 'animate__animated animate__fadeInDown'
                                },
                                hideClass: {
                                    popup: 'animate__animated animate__fadeOutUp'
                                }
                            });
                        }
                        $('#cover-spin').hide();
                    }
                });
            }

        });
    });
</script>