CommonProcessor/CommonProcessor/CommonProcessor/Controllers/DistributorStockController.cs
using CommonProcessor.DAL;
using CommonProcessor.Models.DbContext;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace CommonProcessor.Controllers
{
    public class DistributorStockController : Controller
    {
        private readonly WDMSDal _wDMSDal;
        private readonly RBSYNERGYDal _rBSYNERGYDal;

        public DistributorStockController()
        {
            _wDMSDal = new WDMSDal(new WDSEntities());
            _rBSYNERGYDal = new RBSYNERGYDal(new RBSYNERGYEntities()/*, new RestaurantDBEntities()*/);

        }
        // GET: DistributorStock

        [SessionCheck]
        public ActionResult Index()
        {
            return View();
        }

        public async Task<ActionResult> DistributorStock()
        {
            var data = await _wDMSDal.DistributorStock();

            var returnObj = new
            {
                Data = data,
            };
            return new JsonResult()
            {
                Data = returnObj,
                MaxJsonLength = 86753090,
                JsonRequestBehavior = JsonRequestBehavior.AllowGet
            };

        }

        [SessionCheck]
        public async Task<ActionResult> Electronics_DistributorStock()
        {
            return View();
        }

        public async Task<ActionResult> ElectronicsDistributorStock()
        {
            var data = await _wDMSDal.ElectronicsDistributorStock();

            var returnObj = new
            {
                Data = data,
            };
            return new JsonResult()
            {
                Data = returnObj,
                MaxJsonLength = 86753090,
                JsonRequestBehavior = JsonRequestBehavior.AllowGet
            };

        }

        [SessionCheck]
        public async Task<ActionResult> RetailerModel_WiseStock()
        {
            return View();
        }

        public async Task<ActionResult> RetailerModelWiseStock()
        {
            var data = await _wDMSDal.RetailerModelWiseStock();

            var returnObj = new
            {
                Data = data,
            };
            return new JsonResult()
            {
                Data = returnObj,
                MaxJsonLength = 86753090,
                JsonRequestBehavior = JsonRequestBehavior.AllowGet
            };

        }
    }
}

CommonProcessor/CommonProcessor/CommonProcessor/Views/DistributorStock/Electronics_DistributorStock.cshtml
@{
    ViewBag.Title = "Electronics_DistributorStock";
}

<style>
    .selected {
        background-color: aqua;
    }

    .excelBtn {
        color: #f8f9fa !important;
        background-color: #0d6efd !important;
        border-color: #0d6efd !important;
        padding: .375rem .75rem !important;
        font-size: 1rem !important;
        border-radius: .25rem !important;
    }

    .swal2-icon {
        margin: 0px !important;
    }

    ::placeholder {
        color: red;
        opacity: 1;
    }
</style>

<div class="card-header d-flex align-items-center" style="background-color: cadetblue; color: white;width:auto;">
    <h3 class="h4" style="font-weight: normal">Electronics Distributor Stock</h3>
</div>

<div class="card">
    <div class="card-header">

        <h3>Total Count: <span class="badge bg-success" id="totalCount"></span></h3>

    </div>
    <div class="card-body">
        <div class="row">
            <div style="height: 650px; overflow-x:scroll;overflow-x: auto;width: 100%; overflow-y: auto">
                <table class="table cell-border table-responsive table-hover table-striped" id="recordTable" style="display:none;">
                    <thead>
                        <tr>

                            <th>DistributorName</th>
                            <th>DigitechCode</th>
                            <th>ImportCode</th>
                            <th>Zone</th>
                            <th>RSMName</th>
                            <th>Model</th>
                            <th>ProductyType</th>
                            <th>PresentStock</th>
                            <th>StockValue</th>

                        </tr>
                    </thead>
                    <tbody id="recordTableBody">
                    </tbody>
                    <tfoot>
                        <tr>

                            <th>DistributorName</th>
                            <th>DigitechCode</th>
                            <th>ImportCode</th>
                            <th>Zone</th>
                            <th>RSMName</th>
                            <th>Model</th>
                            <th>ProductyType</th>
                            <th>PresentStock</th>
                            <th>StockValue</th>

                        </tr>
                    </tfoot>
                </table>
            </div>
        </div>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.5.1.js"></script>

<script src="https://cdn.jsdelivr.net/npm/sweetalert2@10"></script>
<link href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" rel="stylesheet" />

<script>
    $(document).ready(function () {
        debugger;
        //$('#recordTable').DataTable();
        Loadstock();
    });

    function Loadstock () {
        cd = (new Date()).toISOString().split('T')[0];

                $.ajax({
                    type: 'GET',
                    contentType: 'application/json',
                    dataType: 'json',
                    url: '@Url.Action("ElectronicsDistributorStock", "DistributorStock")',
                    beforeSend: function () {
                        $('#cover-spin').show();
                    },
                    success: function (data) {

                        var imeiDataList = data.Data.length;
                        $("#totalCount").text(imeiDataList);
                        $("#recordTableBody").html("");
                        $('#recordTable').DataTable().destroy();
                        if (imeiDataList > 0) {
                            for (var i = 0; i < imeiDataList; i++) {

                                $("#recordTableBody").append('<tr>' +

                                    '<td style="width: 11%">' +
                                    data.Data[i].DistributorName +
                                    '</td>' +
                                    '<td style="width: 11%">' +
                                    data.Data[i].DigitechCode +
                                    '</td>' +
                                    '<td style="width: 11%">' +
                                    data.Data[i].ImportCode +
                                    '</td>' +
                                    '<td>' +
                                    data.Data[i].Zone +
                                    '</td>' +
                                    '<td style="width: 11%">' +
                                    data.Data[i].RSMName +
                                    '</td>' +
                                    '<td style="width: 11%">' +
                                    data.Data[i].Model +
                                    '</td>' +
                                    '<td style="width: 11%">' +
                                    data.Data[i].ProductyType +
                                    '</td>' +
                                    '<td style="width: 11%">' +
                                    data.Data[i].PresentStock +
                                    '</td>' +
                                    '<td style="width: 11%">' +
                                    data.Data[i].StockValue +
                                    '</td>' +
                                    '</tr>');
                            }
                            $('#recordTable').show();
                            var table = $('#recordTable').DataTable();

                            new $.fn.dataTable.Buttons(table, {
                                buttons: [
                                    { extend: 'excel', className: 'excelBtn', title: 'Electronics Stock Report', text: 'Click For Excel Export', filename: 'Electronics_Stock_' + cd }
                                ]
                            });

                            table.buttons(0, null).container().prependTo(
                                table.table().container()
                            );

                        } else {
                            swal.fire({
                                title: "Message",
                                text: "Data Not Found",
                                icon: "warning",
                                button: "OK",
                                showClass: {
                                    popup: 'animate__animated animate__fadeInDown'
                                },
                                hideClass: {
                                    popup: 'animate__animated animate__fadeOutUp'
                                }
                            });
                        }
                        $('#cover-spin').hide();
                    }
                });


        }

</script>

CommonProcessor/CommonProcessor/CommonProcessor/Views/DistributorStock/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<style>
    .selected {
        background-color: aqua;
    }

    .excelBtn {
        color: #f8f9fa !important;
        background-color: #0d6efd !important;
        border-color: #0d6efd !important;
        padding: .375rem .75rem !important;
        font-size: 1rem !important;
        border-radius: .25rem !important;
    }

    .swal2-icon {
        margin: 0px !important;
    }

    ::placeholder {
        color: red;
        opacity: 1;
    }
</style>

<div class="card-header d-flex align-items-center" style="background-color: forestgreen; color: white;width:auto;">
    <h3 class="h4" style="font-weight: normal">Mobile Distributor Stock</h3>
</div>

<div class="card">
    <div class="card-header">

        <h3>Total Count: <span class="badge bg-success" id="totalCount"></span></h3>

    </div>
    <div class="card-body">
        <div class="row">
            <div style="height: 650px; overflow-x:scroll;overflow-x: auto;width: 100%; overflow-y: auto">
                <table class="table cell-border table-responsive table-hover table-striped" id="recordTable" style="display:none;">
                    <thead>
                        <tr>

                            <th>DistributorName</th>
                            <th>DigitechCode</th>
                            <th>ImportCode</th>
                            <th>Zone</th>
                            <th>RSMName</th>
                            <th>Model</th>
                            <th>ProductyType</th>
                            <th>PresentStock</th>
                            <th>StockValue</th>

                        </tr>
                    </thead>
                    <tbody id="recordTableBody">
                    </tbody>
                    <tfoot>
                        <tr>

                            <th>DistributorName</th>
                            <th>DigitechCode</th>
                            <th>ImportCode</th>
                            <th>Zone</th>
                            <th>RSMName</th>
                            <th>Model</th>
                            <th>ProductyType</th>
                            <th>PresentStock</th>
                            <th>StockValue</th>

                        </tr>
                    </tfoot>
                </table>
            </div>
        </div>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.5.1.js"></script>

<script src="https://cdn.jsdelivr.net/npm/sweetalert2@10"></script>
<link href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" rel="stylesheet" />

<script>
    $(document).ready(function () {
        debugger;
        //$('#recordTable').DataTable();
        Loadstock();
    });

    function Loadstock () {
        cd = (new Date()).toISOString().split('T')[0];

                $.ajax({
                    type: 'POST',
                    contentType: 'application/json',
                    dataType: 'json',
                    url: '@Url.Action("DistributorStock", "DistributorStock")',
                    beforeSend: function () {
                        $('#cover-spin').show();
                    },
                    success: function (data) {

                        var imeiDataList = data.Data.length;
                        $("#totalCount").text(imeiDataList);
                        $("#recordTableBody").html("");
                        $('#recordTable').DataTable().destroy();
                        if (imeiDataList > 0) {
                            for (var i = 0; i < imeiDataList; i++) {

                                $("#recordTableBody").append('<tr>' +

                                    '<td style="width: 11%">' +
                                    data.Data[i].DistributorName +
                                    '</td>' +
                                    '<td style="width: 11%">' +
                                    data.Data[i].DigitechCode +
                                    '</td>' +
                                    '<td style="width: 11%">' +
                                    data.Data[i].ImportCode +
                                    '</td>' +
                                    '<td>' +
                                    data.Data[i].Zone +
                                    '</td>' +
                                    '<td style="width: 11%">' +
                                    data.Data[i].RSMName +
                                    '</td>' +
                                    '<td style="width: 11%">' +
                                    data.Data[i].Model +
                                    '</td>' +
                                    '<td style="width: 11%">' +
                                    data.Data[i].ProductyType +
                                    '</td>' +
                                    '<td style="width: 11%">' +
                                    data.Data[i].PresentStock +
                                    '</td>' +
                                    '<td style="width: 11%">' +
                                    data.Data[i].StockValue +
                                    '</td>' +
                                    '</tr>');
                            }
                            $('#recordTable').show();
                            var table = $('#recordTable').DataTable();

                            new $.fn.dataTable.Buttons(table, {
                                buttons: [
                                    { extend: 'excel', className: 'excelBtn', title: 'Distributor Stock Report_' + cd, text: 'Click For Excel Export', filename: 'Distributor_Stock_' + cd }
                                ]
                            });

                            table.buttons(0, null).container().prependTo(
                                table.table().container()
                            );

                        } else {
                            swal.fire({
                                title: "Message",
                                text: "Data Not Found",
                                icon: "warning",
                                button: "OK",
                                showClass: {
                                    popup: 'animate__animated animate__fadeInDown'
                                },
                                hideClass: {
                                    popup: 'animate__animated animate__fadeOutUp'
                                }
                            });
                        }
                        $('#cover-spin').hide();
                    }
                });


        }

</script>

CommonProcessor/CommonProcessor/CommonProcessor/Views/DistributorStock/RetailerModel_WiseStock.cshtml
@{
    ViewBag.Title = "RetailerModel_WiseStock";
}


<style>
    .selected {
        background-color: aqua;
    }

    .excelBtn {
        color: #f8f9fa !important;
        background-color: #0d6efd !important;
        border-color: #0d6efd !important;
        padding: .375rem .75rem !important;
        font-size: 1rem !important;
        border-radius: .25rem !important;
    }

    .swal2-icon {
        margin: 0px !important;
    }

    ::placeholder {
        color: red;
        opacity: 1;
    }
</style>

<div class="card-header d-flex align-items-center" style="background-color: cadetblue; color: white;width:auto;">
    <h3 class="h4" style="font-weight: normal">WDS Retailer Stock</h3>
</div>

<div class="card">
    <div class="card-header">

        <h3>Total Count: <span class="badge bg-success" id="totalCount"></span></h3>

    </div>
    <div class="card-body">
        <div class="row">
            <div style="height: 650px; overflow-x:scroll;overflow-x: auto;width: 100%; overflow-y: auto">
                <table class="table cell-border table-responsive table-hover table-striped" id="recordTable" style="display:none;">
                    <thead>
                        <tr>

                            <th>DistributorNameCellCom</th>
                            <th>DigitechCode</th>
                            <th>RetailerName</th>
                            <th>RetailerId</th>
                            <th>Model</th>
                            <th>StockQTY</th>

                        </tr>
                    </thead>
                    <tbody id="recordTableBody">
                    </tbody>
                    <tfoot>
                        <tr>

                            <th>DistributorNameCellCom</th>
                            <th>DigitechCode</th>
                            <th>RetailerName</th>
                            <th>RetailerId</th>
                            <th>Model</th>
                            <th>StockQTY</th>

                        </tr>
                    </tfoot>
                </table>
            </div>
        </div>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.5.1.js"></script>

<script src="https://cdn.jsdelivr.net/npm/sweetalert2@10"></script>
<link href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" rel="stylesheet" />

<script>
    $(document).ready(function () {
        debugger;
        //$('#recordTable').DataTable();
        Loadstock();
    });

    function Loadstock () {
        cd = (new Date()).toISOString().split('T')[0];

                $.ajax({
                    type: 'GET',
                    contentType: 'application/json',
                    dataType: 'json',
                    url: '@Url.Action("RetailerModelWiseStock", "DistributorStock")',
                    beforeSend: function () {
                        $('#cover-spin').show();
                    },
                    success: function (data) {

                        var imeiDataList = data.Data.length;
                        $("#totalCount").text(imeiDataList);
                        $("#recordTableBody").html("");
                        $('#recordTable').DataTable().destroy();
                        if (imeiDataList > 0) {
                            for (var i = 0; i < imeiDataList; i++) {

                                $("#recordTableBody").append('<tr>' +

                                    '<td style="width: 11%">' +
                                    data.Data[i].DistributorNameCellCom +
                                    '</td>' +
                                    '<td style="width: 11%">' +
                                    data.Data[i].DigitechCode +
                                    '</td>' +
                                    '<td style="width: 11%">' +
                                    data.Data[i].RetailerName +
                                    '</td>' +
                                    '<td style="width: 11%">' +
                                    data.Data[i].RetailerId +
                                    '</td>' +
                                    '<td style="width: 11%">' +
                                    data.Data[i].Model +
                                    '</td>' +
                                    '<td style="width: 11%">' +
                                    data.Data[i].StockQTY +
                                    '</td>' +
                                    '</tr>');
                            }
                            $('#recordTable').show();
                            var table = $('#recordTable').DataTable();

                            new $.fn.dataTable.Buttons(table, {
                                buttons: [
                                    { extend: 'excel', className: 'excelBtn', title: 'WDS Retailer Stock Report', text: 'Click For Excel Export', filename: 'WDS_Retailer_Stock_' + cd }
                                ]
                            });

                            table.buttons(0, null).container().prependTo(
                                table.table().container()
                            );

                        } else {
                            swal.fire({
                                title: "Message",
                                text: "Data Not Found",
                                icon: "warning",
                                button: "OK",
                                showClass: {
                                    popup: 'animate__animated animate__fadeInDown'
                                },
                                hideClass: {
                                    popup: 'animate__animated animate__fadeOutUp'
                                }
                            });
                        }
                        $('#cover-spin').hide();
                    }
                });


        }

</script>