CommonProcessor/CommonProcessor/CommonProcessor/Controllers/NonWarrantyImeiProcessorController.cs
using CommonProcessor.DAL;
using CommonProcessor.Models.DbContext;
using CommonProcessor.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace CommonProcessor.Controllers
{
    public class NonWarrantyImeiProcessorController : Controller
    {
        private readonly RBSYNERGYDal _rBSYNERGYDal;

        public NonWarrantyImeiProcessorController()
        {
            _rBSYNERGYDal = new RBSYNERGYDal(new RBSYNERGYEntities());

        }

        // GET: NonWarrantyImeiProcessor
        [SessionCheck]
        public ActionResult Index()
        {
            return View();
        }

        public async Task<ActionResult> GetAllModelList()
        {
            var data = await _rBSYNERGYDal.GetAllModelList();

            var returnObj = new
            {
                Data = data,
            };
            return new JsonResult()
            {
                Data = returnObj,
                MaxJsonLength = 86753090,
                JsonRequestBehavior = JsonRequestBehavior.AllowGet
            };

        }

        public async Task<ActionResult> GetImei1Info(string Barcode)
        {
            var data = await _rBSYNERGYDal.GetImei1Info(Barcode);

            var returnObj = new
            {
                Data = data,
            };
            return new JsonResult()
            {
                Data = returnObj,
                MaxJsonLength = 86753090,
                JsonRequestBehavior = JsonRequestBehavior.AllowGet
            };

        }

        public ActionResult InsertDealer(List<Non_Warranty_IMEI_Processor_ViewModel> modelList)
        {
            string result = "Error! Insert Data Is Not Complete!";
            RBSYNERGYEntities db = new RBSYNERGYEntities();

            if (modelList != null)
            {
                foreach (var item in modelList)
                {
                    var BarCodeInv = db.tblBarCodeInvs.Where(x => x.BarCode == item.IMEI1 || x.BarCode == item.IMEI2).FirstOrDefault();

                    //var DealerDetails = db.tblDealerDistributionDetails.Where(x => x.BarCode == item.BarCode || x.BarCode2 == item.BarCode).FirstOrDefault();

                    //DealerDetails.DealerCode = item.NewDealerCode;

                    if (BarCodeInv == null)
                    {
                        var barCodeInv = new tblBarCodeInv
                        {
                            RecID = Guid.NewGuid(),
                            PrintDate = Convert.ToDateTime(Convert.ToDateTime(DateTime.Now.Date).ToString("yyyy-MM-dd")),
                            ProductType = "Cell Phone",
                            Model = item.Model,
                            Color = item.Color,
                            BarCode = item.IMEI1,
                            BarCode2 = item.IMEI2,
                            DelieveredTo = item.DelieveredTo,
                            PrintSuccess = true,
                            AddedBy = "raihan",
                            DateAdded = Convert.ToDateTime(Convert.ToDateTime(DateTime.Now.Date).ToString("yyyy-MM-dd")),
                            Updatedby = item.UpdatedBy,
                            DateUpdated = DateTime.Now.ToString("yyyyMMdd"),
                            Grade = item.Grade
                        };

                        db.tblBarCodeInvs.Add(barCodeInv);
                        db.SaveChanges();
                        result = "Successfully!! Data Insert Is Complete!";
                    }

                }
            }

            return Json(result, JsonRequestBehavior.AllowGet);
        }
    }
}

CommonProcessor/CommonProcessor/CommonProcessor/Views/NonWarrantyImeiProcessor/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<style>
    .selected {
        background-color: aqua;
    }

    .excelBtn {
        color: #f8f9fa !important;
        background-color: #0d6efd !important;
        border-color: #0d6efd !important;
        padding: .375rem .75rem !important;
        font-size: 1rem !important;
        border-radius: .25rem !important;
    }

    .swal2-icon {
        margin: 0px !important;
    }

    ::placeholder {
        color: red;
        opacity: 1;
    }
</style>

<br />
<div class="card">
    <div class="card-body">

        <div class="row">
            <div class="col-sm-4">
                <div class="input-group mb-3">
                    <span class="input-group-text" id="type"><b>Model</b></span>
                    <select class="form-control" style="width:70%;" id="ddlModel">
                    </select>
                </div>
            </div>

            <div class="col-sm-4">
                <div class="input-group mb-3">
                    <span class="input-group-text" id="basic-addon1"><b>Updated By</b></span>
                    <select class="form-control" id="ddlUpdatedBy">
                        <option>Not Tracable</option>
                        <option>Order 1</option>
                        <option>Order 2</option>
                        <option>Order 3</option>
                        <option>Order 4</option>
                        <option>Order 5</option>
                        <option>Order 6</option>
                        <option>Order 7</option>
                        <option>Order 8</option>
                        <option>Order 9</option>
                        <option>Order 10</option>
                    </select>
                </div>
            </div>
        </div>
    </div>
</div>
<br />

<div class="card">
    <div class="card-body">

        <div class="row">
            <div class="col-sm-4">
                <div class="input-group mb-3">
                    <span class="input-group-text" id="basic-addon1"><b>Delievered To</b></span>
                    <select class="form-control" id="ddlDelieveredTo">
                        <option>Not Tracable</option>
                        <option>CKD</option>
                        <option>SKD</option>
                    </select>
                </div>
            </div>

            <div class="col-sm-4">
                <div class="input-group mb-3">
                    <span class="input-group-text" id="basic-addon1"><b>Grade</b></span>
                    <select class="form-control" id="ddlGrade">
                        <option>Exchange IMEI</option>
                        <option>CPSD Made handset</option>
                        <option>Not Tracable</option>
                        <option>A</option>
                        <option>B</option>
                        <option>C</option>
                        <option>D</option>
                        <option>E</option>
                        <option>F</option>
                    </select>
                </div>
            </div>
        </div>
    </div>
</div>
<br />

<div class="card">
    <div class="card-body">

        <div class="row">
            <div class="col-sm-3">
                <div class="input-group mb-3">
                    <span class="input-group-text" id="basic-addon1"><b>IMEI 1</b></span>
                    <input type="text" class="form-control" id="Barcode" placeholder="Enter IMEI 1" maxlength="15" oninput="this.value = this.value.replace(/[^0-9.]/g, '').replace(/(\..*)\./g, '$1');" />
                </div>
            </div>

            <div class="col-sm-3">
                <div class="input-group mb-3">
                    <span class="input-group-text" id="basic-addon1"><b>IMEI 2</b></span>
                    <input type="text" class="form-control" id="Barcode2" placeholder="Enter IMEI 2" maxlength="15" oninput="this.value = this.value.replace(/[^0-9.]/g, '').replace(/(\..*)\./g, '$1');" />
                </div>
            </div>

            <div class="col-sm-3">
                <div class="input-group mb-3">
                    <span class="input-group-text" id="basic-addon1"><b>Color</b></span>
                    <input type="text" class="form-control" id="Color" placeholder="Enter Color" />
                </div>
            </div>


            <div class="col-sm-3">
                <div class="form-check form-switch">
                    <button type="button" class="btn btn-outline-info btn-group-lg col-md-6" id="addToList"><strong>Add Data</strong></button>
                </div>
            </div>

        </div>
    </div>
</div>
<br />

 &nbsp;
<table id="detailsTable" class="table table-bordered table-hover table-responsive">
    <thead>
        <tr>
            @*<th style="width:20%">BarCode</th>
                <th style="width:20%">BarCode2</th>
                <th style="width:20%">Model</th>
                <th style="width:20%">Dealer Code</th>*@

            <th style="width:20%">Model</th>
            <th style="width:15%">UpdatedBy</th>
            <th style="width:10%">DelieveredTo</th>
            <th style="width:15%">Grade</th>
            <th style="width:12%">IMEI1</th>
            <th style="width:12%">IMEI2</th>
            <th style="width:12%">Color</th>

            <th style="width:10%">Action</th>
        </tr>
    </thead>
    <tbody></tbody>
</table>

<div class="row">
    <label class="col-md-11 form-control-label"></label>
    <button id="btnSave" type="button" class="btn btn-success"><strong>Save Data</strong></button>
</div>


@*<div class="col-sm-offset-6">
        <div class="form-check form-switch">
            <label class="col-md-11 form-control-label"></label>
            <button id="btnSave" type="button" class="btn btn-outline-success"><strong>Save Data</strong></button>
        </div>
    </div>*@

<script src="https://code.jquery.com/jquery-3.5.1.js"></script>

<script src="https://cdn.jsdelivr.net/npm/sweetalert2@10"></script>
<link href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" rel="stylesheet" />

<script>
    $(document).ready(function () {
        //$('#recordTable').DataTable();

        $("#ddlModel").select2({

        });

        $.ajax({

            type: "GET",
            url: '@Url.Action("GetAllModelList", "NonWarrantyImeiProcessor")',
            //data: "{}",
            data: { ddldealer: $("#ddlModel").val() },
            success: function (data) {
                debugger;
                var s = '';//<option value="0">ALL</option>
                for (var i = 0; i < data.Data.length; i++) {
                    s += '<option value="' + data.Data[i].Model + '">' + data.Data[i].Model + '</option>';
                }
                $("#ddlModel").html(s);
            }
        });

        $("#Barcode").change(function(){
            //debugger;
            var str = $("#Barcode").val();
            if (str.length == 15) {
                $.ajax({
                    url: '@Url.Action("GetImei1Info", "NonWarrantyImeiProcessor")',
                    dataType: "json",
                    data: { Barcode: $("#Barcode").val() },
                    success: function (data) {
                        if (data.Data != null) {

                            alert("Duplicate");

                        }
                        else {
                            alert("New IMEI1");
                        }
                    }
                });
            }
            else {
                alert("Give Correct IMEI1");
                $("#Barcode").val('');
            }
        });
        $("#Barcode2").change(function(){
            //debugger;
            var str = $("#Barcode2").val();
                if (str.length == 15) {
                    $.ajax({
                        url: '@Url.Action("GetImei1Info", "NonWarrantyImeiProcessor")',
                        dataType: "json",
                        data: { Barcode: $("#Barcode2").val() },
                        success: function (data) {
                            if (data.Data != null) {

                                alert("Duplicate");

                            }
                            else {
                                alert("New IMEI2");
                            }
                        }
                    });
                }
                else {
                    alert("Give Correct IMEI2");
                    $("#Barcode2").val('');
                }
        });

        $("#addToList").click(function (e) {
            //e.preventDefault();
            var a = 0;
            debugger;
            if ($.trim($("#Barcode").val()) == "" || $.trim($("#Barcode2").val()) == "") return;

            var
                Model = $("#ddlModel").val(),
                UpdatedBy = $("#ddlUpdatedBy").val(),
                DelieveredTo = $("#ddlDelieveredTo").val(),
                Grade = $("#ddlGrade").val(),
                IMEI1 = $("#Barcode").val(),
                IMEI2 = $("#Barcode2").val(),
                Color = $("#Color").val(),
                detailsTableBody = $("#detailsTable tbody");

            var tempData = '<tr><td>' + Model + '</td><td>' + UpdatedBy + '</td><td>' + DelieveredTo + '</td><td>' + Grade + '</td><td>' + IMEI1 + '</td><td>' + IMEI2 + '</td><td>' + Color + '</td><td><a data-itemId="0" href="#" class="deleteItem">Remove</a></td></tr>';

            $.each($("#detailsTable tbody tr"), function () {
                debugger;
                var AbarCode = $(this).find('td:eq(4)').text();
                var AbarCode2 = $(this).find('td:eq(5)').text();
                if (AbarCode == IMEI1 || AbarCode2 == IMEI2) {
                    alert("Already exist!.");
                    a = 1;
                    return false;
                }
            });
            if (a == 0) {
                detailsTableBody.append(tempData);

                clearItem();
            }

        });

        function InsertDealer(data) {
        return $.ajax({
            contentType: 'application/json; charset=utf-8',
            dataType: 'json',
            type: 'POST',
            url: '@Url.Action("InsertDealer", "NonWarrantyImeiProcessor")',
            data: data,
            success: function (result) {
                alert(result);
                location.reload();
            },
            error: function () {
                alert("Error!")
            }
        });
    }

        $("#btnSave").click(function (e) {
            debugger;
            var orderArr = [];
            orderArr.length = 0;

            $.each($("#detailsTable tbody tr"), function () {
                orderArr.push({
                    Model: $(this).find('td:eq(0)').text(),
                    UpdatedBy: $(this).find('td:eq(1)').text(),
                    DelieveredTo: $(this).find('td:eq(2)').text(),
                    Grade: $(this).find('td:eq(3)').text(),
                    IMEI1: $(this).find('td:eq(4)').text(),
                    IMEI2: $(this).find('td:eq(5)').text(),
                    Color: $(this).find('td:eq(6)').text()
                });
            });


            var data = JSON.stringify({
                modelList: orderArr
            });

            $.when(InsertDealer(data)).then(function (response) {
                console.log(response);
            }).fail(function (err) {
                console.log(err);
            });
        });

        $(document).on('click', 'a.deleteItem', function (e) {
            e.preventDefault();
            var $self = $(this);
            if ($(this).attr('data-itemId') == "0") {
                $(this).parents('tr').css("background-color", "#ff6347").fadeOut(800, function () {
                    $(this).remove();
                });
            }
        });

        function clearItem() {
            $("#Barcode").val('');
            $("#Barcode2").val('');
            $("#Color").val('');
        }

    });
</script>