CommonProcessor/CommonProcessor/CommonProcessor/Controllers/BarCodeScannerController.cs
using CommonProcessor.DAL;
using CommonProcessor.Models.DbContext;
using CommonProcessor.ViewModel;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace CommonProcessor.Controllers
{
    public class BarCodeScannerController : Controller
    {
        private readonly RBSYNERGYDal _rBSYNERGYDal;

        public BarCodeScannerController()
        {
            _rBSYNERGYDal = new RBSYNERGYDal(new RBSYNERGYEntities());

        }

        // GET: BarCodeScanner
        [SessionCheck]
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> GetBarcodeInformation(string barCode)
        {
            var modelData = JsonConvert.DeserializeObject<List<BarCodeScannerViewModel>>(barCode);
            
            var data = await _rBSYNERGYDal.GetBarcodeInformation(modelData);            

            var returnObj = new
            {
                Data = data,
            };
            return new JsonResult()
            {
                Data = returnObj,
                MaxJsonLength = 86753090,
                JsonRequestBehavior = JsonRequestBehavior.AllowGet
            };

        }
    }
}

CommonProcessor/CommonProcessor/CommonProcessor/Views/BarCodeScanner/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<style>
    .selected {
        background-color: aqua;
    }

    .excelBtn {
        color: #f8f9fa !important;
        background-color: #0d6efd !important;
        border-color: #0d6efd !important;
        padding: .375rem .75rem !important;
        font-size: 1rem !important;
        border-radius: .25rem !important;
    }

    .swal2-icon {
        margin: 0px !important;
    }
</style>

<br />
<div class="card">
    <div class="card-body">

        <div class="row">
            <div class="card card-chart" id="divMC" style="text-align: center;">
                <div class="card-header card-header-rose">
                    Copy Multiple Barcode And Search
                </div>
                <div class="card-body">
                    <div class="form-group">
                        <textarea id="dataMulti" style="height: 100px; font-size: 20px;" placeholder="Please Use Enter for each IMEI"></textarea>
                    </div>

                </div>
            </div>
            @*<div class="col-sm-4">
                    <div class="input-group mb-4">
                        <span class="input-group-text" id="basic-addon1"><b>BarCode</b></span>
                        <input type="text" class="form-control" id="Barcode" placeholder="Enter BarCode" maxlength="15" oninput="this.value = this.value.replace(/[^0-9.]/g, '').replace(/(\..*)\./g, '$1');" />
                    </div>
                </div>*@

        </div>
        <div class="col-sm-3">
            <div class="input-group mb-3">
                <input type="button" class="btn btn-info btn-group-lg col-md-3" id="BtnSearch" value="Search" />&nbsp;&nbsp;
                <input type="button" id="btnClear" class="btn btn-danger" value="Clear All" />
            </div>
        </div>
    </div>
</div>
<br />
<div class="card">

    <div class="card-body">
        <div class="row">
            <div style="height: 550px; overflow-x:scroll;overflow-x: auto; display:none; " id="tabresult">

                @*<div>
                        <button id="exportReport" style="background-color:#4CAF50;color:white;">
                            Export to Excel
                        </button>
                        <br />
                        <br />
                    </div>*@

                <button class="btn btn-outline-info" onclick="ExportToExcel('xlsx')" style="background-color:#4CAF50;color:white;">Export to excel</button>

                <table class="table cell-border table-responsive table-hover table-striped" id="recordTable">
                    <thead>
                        <tr>

                            <th>BarCode</th>
                            <th>BarCode2</th>
                            <th>Model</th>
                            <th>Sale_Date</th>
                            <th>Addedby</th>
                            <th>DealerCode</th>
                            <th>DealerName</th>
                            <th>BPPhoneNumber</th>
                            <th>BPName</th>
                            <th>RetailerName</th>
                            <th>Replacement</th>
                            <th>Registrationdate</th>
                            <th>Action</th>

                        </tr>
                    </thead>
                    <tbody id="recordTableBody">
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.5.1.js"></script>

<script src="https://cdn.jsdelivr.net/npm/sweetalert2@10"></script>

<script type="text/javascript" src="https://unpkg.com/xlsx@0.15.1/dist/xlsx.full.min.js"></script>

<link href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" rel="stylesheet" />

<script>
    $(document).ready(function () {
        //$('#recordTable').DataTable();

        $("#btnClear").click(function (e) {
            $("#dataMulti").val("");

        });

        $("#BtnSearch").click(function (e) {
            debugger;

            var multiData = [];

            $.each($('#dataMulti').val().split(/\n/), function (i, line) {
                if (line) {
                    multiData.push({

                        BarCode: line

                    });
                }
            });

            var finaldata = JSON.stringify(multiData);

            $("#tabresult").show();
            //var Barcode = $("#Barcode").val();
            var Barcode = $("#dataMulti").val();
            var dataList = JSON.stringify({ Barcode: finaldata });

            if (Barcode != "") {

                $.ajax({
                    type: 'POST',
                    contentType: 'application/json',
                    dataType: 'json',
                    url: '@Url.Action("GetBarcodeInformation", "BarCodeScanner")',
                    data: dataList,
                    //beforeSend: function () {
                    //    $('#cover-spin').show();
                    //},
                    success: function (data) {

                        var imeiDataList = data.Data.length;
                        if (imeiDataList > 0) {
                            for (var i = 0; i < imeiDataList; i++)
                            { 
                                var a = 0;
                                debugger;
                                var cSharpAddedDate = data.Data[i].Sale_Date;
                                var m = cSharpAddedDate != null ? new Date(parseInt(cSharpAddedDate.replace(/[^0-9 +]/g, ''))) : null;
                                var addedDateString = m!= null ? m.getFullYear() + "-" + (m.getMonth() + 1) + "-" + m.getDate() : null;

                                var cSharpRegistrationDate = data.Data[i].Registrationdate;
                                var n = cSharpRegistrationDate != null ? new Date(parseInt(cSharpRegistrationDate.replace(/[^0-9 +]/g, ''))) : null;
                                var RegistrationDateString = n != null ? n.getFullYear() + "-" + (n.getMonth() + 1) + "-" + n.getDate() : null;

                                debugger;
                                if ($.trim($("#dataMulti").val()) == "") return;

                                var BarCode = data.Data[i].Barcode,
                                    BarCode2 = data.Data[i].BarCode2,
                                    Model = data.Data[i].Model,
                                    Sale_Date = addedDateString,
                                    Addedby = data.Data[i].Addedby,
                                    DealerCode = data.Data[i].DealerCode,
                                    DealerName = data.Data[i].DealerName,
                                    BPPhoneNumber = data.Data[i].BPPhoneNumber,
                                    BPName = data.Data[i].BPName,
                                    RetailerName = data.Data[i].RetailerName,
                                    Replacement = data.Data[i].Replacement,

                                    Registrationdate = RegistrationDateString,
                                    recordTableBody = $("#recordTable tbody");

                                var tempData = '<tr><td>' + BarCode + '</td><td>' + BarCode2 + '</td><td>' + Model + '</td><td>' + Sale_Date + '</td><td>' + Addedby + '</td><td>' + DealerCode + '</td><td>' + DealerName + '</td><td>' + BPPhoneNumber + '</td><td>' + BPName + '</td><td>' + RetailerName + '</td><td>' + Replacement + '</td><td>' + Registrationdate + '</td><td><a data-itemId="0" href="#" class="deleteItem">Remove</a></td></tr>';


                                $.each($("#recordTable tbody tr"), function () {
                                    debugger;
                                    var AbarCode = $(this).find('td:eq(0)').text();
                                    var AbarCode2 = $(this).find('td:eq(1)').text();
                                    if (AbarCode == BarCode || AbarCode2 == BarCode2) {
                                        alert("Already exist!.");
                                        a = 1;
                                        return false;
                                    }
                                });
                                if (a == 0) {
                                    recordTableBody.append(tempData);
                                    //clearItem();
                                    //$("#dataMulti").val("");
                                }

                            }
                        }

                    }

                });

            }

        });

        $(document).on('click', 'a.deleteItem', function (e) {
            e.preventDefault();
            var $self = $(this);
            if ($(this).attr('data-itemId') == "0") {
                $(this).parents('tr').css("background-color", "#ff6347").fadeOut(800, function () {
                    $(this).remove();
                });
            }
        });


    });

    function ExportToExcel(type, fn, dl) {
        debugger;
        var elt = document.getElementById('recordTable');
        var wb = XLSX.utils.table_to_book(elt, { sheet: "Report" });
        return dl ?
            XLSX.write(wb, { bookType: type, bookSST: true, type: 'base64' }) :
            XLSX.writeFile(wb, fn || ('BarCode_Report.' + (type || 'xlsx')));
    }



</script>